language: java
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: opengrok
    token:
      secure: ayjmifQPQgKt/ICGfKtLpa8LwBAXZlxKwaPyjvXDRHyf3lbXGKkOCspH/wSoersoV4ZLt5UfSGKeFh1MS0IXAwUOcPTcV3/DUmycJjxZ5z9KjgGKsu0Spo1xZWioS+p1bzN6cJcNlwihE97idLhVSvDProf6L+pn0dqw8Lfz2k0=
jobs:
  include:
  - stage: docker
    name: Docker image build
    dist: xenial
    jdk: openjdk11
    install: true
    services:
    - docker
    before_install: dev/before_install
    script: dev/docker.sh
  - stage: javadoc
    name: Upload javadocs to Github pages
    os: linux
    dist: xenial
    jdk: openjdk11
    script: dev/javadoc.sh
    install: true
    if: repo = "oracle/opengrok" AND tag IS NOT present
